name: build-aur-package

on:
  workflow_dispatch:
    inputs:
      package_name:
        type: string
        required: true
        description: "Package name"
        
env:
  PKGDEST: "/tmp"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          cd /tmp
          echo ${{ github.event.inputs.package_name }} | sed 's/,/\n/g' | awk '{print "git clone --depth 1 https://aur.archlinux.org/"$1".git" }' | bash
          chown builder -R /tmp
          chown builder -R ./${{ github.event.inputs.package_name }}
      - name: Build
        run: |
          echo ${{ github.event.inputs.package_name }} | sed 's/,/\n/g' | awk '{ print "cd "$1"; su builder -c \"yes '' | makepkg --noconfirm -sc\" ; pacman --noconfirm -U /tpm/"$1"*.pkg.tar.zst" }' | bash
#          su builder -c "yes '' | makepkg --noconfirm -sc"
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: aur-package
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
