name: build-aur-package

on:
  workflow_dispatch:
    inputs:
      package_name:
        type: string
        required: true
        description: "Package name"
        
env:
  PKGDEST: "/tmp"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          git clone --depth 1 https://aur.archlinux.org/${{ github.event.inputs.package_name }}.git
          chown builder -R /tmp
      - name: Build
        run: |
          cd ${{ github.event.inputs.package_name }}
          su builder -c "yes '' | makepkg --noconfirm -sc"
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: aur-package
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
