name: build-backstage

on:
  workflow_dispatch:
env:
  PKGDEST: "/tmp/backstage"
  
jobs:
  build:
    runs-on: ubuntu-latest
#    container: archlinux:latest
    steps:
#      - name: Check out repository
#        uses: actions/checkout@v4
      - name: Check out backstage repository
        uses: actions/checkout@v4
        with:
          repository: backstage/backstage
          path: backstage
      - name: Prepare for build
        run: |
          sudo apt update
          sudo apt install yarn
      - name: Build app
        run: |
          cd backstage
          yarn install
          yarn tsc
          yarn build:backend
#      - uses: actions/upload-artifact@v4
#        with:
#          name: linux-lqx
#          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
