name: build-backstage

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#      - name: Check out backstage repository
#        uses: actions/checkout@v4
#        with:
#          repository: backstage/backstage
#          ref: v1.22.2
#          path: backstage
      - name: Prepare for build
        run: |
          sudo apt update
          sudo apt install yarn
          sudo apt install nodejs
          sudo apt install npm
      - name: Build app
        run: |
          echo "my-backstage-app" | npx @backstage/create-app@latest
          ls -l
#          yarn install
#          yarn tsc
#          yarn build:backend
#      - name: Build Container Image
#        run: |
#          cd backstage
#          docker image build . -f packages/backend/Dockerfile --tag backstage
#          docker images
#          docker save backstage > /tmp/backstage.tar
#      - uses: actions/upload-artifact@v4
#        with:
#          name: backstage
#          path: /tmp/backstage.tar
