name: build-backstage

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out backstage repository
        uses: actions/checkout@v4
        with:
          repository: backstage/backstage
          ref: v1.22.2
          path: backstage
      - name: Prepare for build
        run: |
          sudo apt update
          curl -sL https://deb.nodesource.com/setup_16.x -o /tmp/nodesource_setup.sh
          sudo bash /tmp/nodesource_setup.sh
          sudo apt install nodejs
          node -v
          sudo apt install npm
          sudo apt install yarn
      - name: Build app
        run: |
          cd backstage
          yarn set version 1.22.19
          echo "app" | npx @backstage/create-app@latest
          cd app
          yarn install --frozen-lockfile
          yarn tsc
          yarn build:backend --config ../../app-config.yaml
      - name: Build container image
        run: |
          cd backstage/app
          yarn set version 1.22.19
          sed -i 's/node:18/node:16/g' ./packages/backend/Dockerfile
          docker image build . -f packages/backend/Dockerfile --tag backstage
          docker images
          docker save backstage > /tmp/backstage.tar
#          yarn set version 1.22.19
#          cd app
#          sed -i 's/, "--config", "app-config.production.yaml"/ /g' packages/backend/Dockerfile
      - uses: actions/upload-artifact@v4
        with:
          name: backstage
          path: /tmp/backstage.tar
