name: build-backstage

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare for build
        run: |
          sudo apt update
          sudo apt install yarn
          sudo apt install nodejs
          sudo apt install npm
      - name: Build app
        run: |
          echo "app" | npx @backstage/create-app@latest
          cd app
          yarn install --frozen-lockfile
          yarn tsc
          yarn build:backend --config ../../app-config.yaml
      - name: Build Container Image
        run: |
          cd app
          docker image build . -f packages/backend/Dockerfile --tag backstage
          docker images
          docker save backstage > /tmp/backstage.tar
      - uses: actions/upload-artifact@v4
        with:
          name: backstage
          path: /tmp/backstage.tar
