name: build-backscrub-git

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp"
  VERBOSE: "1"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          curl -L https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=backscrub-git -o PKGBUILD
          sed -i 's/tensorflow\/tensorflow/tensorflow\/tensorflow#tag=v2.8.4/g' PKGBUILD
          sed -i 's/backscrub\.git/backscrub\.git#tag=v0.3.0/g' PKGBUILD
          sed -i '/cmake --build/i \ \ cat ${pkgname}/build/abseil-cpp/absl/synchronization/internal/graphcycles.h >> tmp.h' PKGBUILD
          sed -i '/cmake --build/i \ \ cat ${pkgname}/build/ruy/ruy/block_map.h >> tmp2.h' PKGBUILD
          sed -i '/cmake --build/i \ \ mv tmp.h ${pkgname}/build/abseil-cpp/absl/synchronization/internal/graphcycles.h' PKGBUILD
          sed -i '/cmake --build/i \ \ mv tmp2.h ${pkgname}/build/ruy/ruy/block_map.h ' PKGBUILD
          echo "#include <limits>" > tmp.h
          echo "#include <stdexcept>" >> tmp.h
          cp tmp.h tmp2.h
          cat PKGBUILD
          chown builder -R ..
          chown builder -R /tmp
          pacman --noconfirm -U https://archive.archlinux.org/packages/g/gcc/gcc-11.2.0-4-x86_64.pkg.tar.zst https://archive.archlinux.org/packages/g/gcc-libs/gcc-libs-11.2.0-4-x86_64.pkg.tar.zst https://archive.archlinux.org/packages/c/cmake/cmake-3.22.2-1-x86_64.pkg.tar.zst
      - name: Build
        run: |
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
      - uses: actions/upload-artifact@v3
        with:
          name: backscrub-git
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
