name: build-backscrub-git

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp"
  VERBOSE: "1"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          curl -L https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=backscrub-git -o PKGBUILD
          sed -i 's/tensorflow\/tensorflow/tensorflow\/tensorflow#tag=v2.8.4/g' PKGBUILD
          sed -i 's/cmake \\/cmake -DCMAKE_VERBOSE_MAKEFILE=1 \\/g' PKGBUILD
          chown builder -R ..
          chown builder -R /tmp
#          pacman --noconfirm -U https://archive.archlinux.org/packages/g/gcc12/gcc12-12.2.1-1-x86_64.pkg.tar.zst
      - name: Build
        run: |
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
      - uses: actions/upload-artifact@v3
        with:
          name: backscrub-git
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
