name: build-lqx2

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp/pkgbuild-linux-lqx"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Check out linux-lqx repository
        uses: actions/checkout@v3
        with:
          repository: blacksky3/linux-lqx
          path: linux-lqx
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          git clone https://aur.archlinux.org/linux-xanmod.git
          chown builder -R ..
          chown builder -R /tmp
          su builder -c "gpg --recv 38DBBDC86092693E"
      - name: Build kernel
        run: |
          cd linux-lqx/pds 
          su builder -c "yes '' | env _compiler=2 makepkg --noconfirm -sc"
      - uses: actions/upload-artifact@v3
        with:
          name: linux-lqx
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
