name: build-liquorix

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 13
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Prepare for build
        run: |
           git clone https://aur.archlinux.org/linux-lqx.git
           sed -i -e "/export KBUILD_BUILD_HOST=archlinux/i export BUILD_FLAGS=(CC=clang CXX=clang++ HOSTCC=clang HOSTCXX=clang++ LD=ld.lld LLVM=1 LLVM_IAS=1)" linux-lqx/PKGBUILD
           sed -i 's/make /make ${BUILD_FLAGS[*]} /g' linux-lqx/PKGBUILD
           sed -i -e "/scripts\/config --disable CONFIG_SCHED_BMQ/i \ \t\tscripts/config --disable CONFIG_CPU_FREQ_DEFAULT_GOV_PERFORMANCE" linux-lqx/PKGBUILD
           cat linux-lqx/PKGBUILD
#           sed -i -e "160i \ \t\tscripts/config --enable CONFIG_CPU_FREQ_DEFAULT_GOV_SCHEDUTIL" linux-lqx/PKGBUILD
#           sed -i -e "160i \ \t\tscripts/config --enable CONFIG_CPU_FREQ_GOV_SCHEDUTIL" linux-lqx/PKGBUILD
#           sed -i -e "160i \ \t\tscripts/config --enable CONFIG_HAVE_GCC_PLUGINS" linux-lqx/PKGBUILD
#           sed -i -e "160i \ \t\tscripts/config --disable CONFIG_LTO_CLANG_THIN" linux-lqx/PKGBUILD
#           sed -i -e "160i \ \t\tscripts/config --disable CONFIG_LTO_CLANG_THIN" linux-lqx/PKGBUILD
#           sed -i -e "160i \ \t\tscripts/config --enable CONFIG_LTO_CLANG_FULL" linux-lqx/PKGBUILD
#           sed -i -e "160i \ \t\tscripts/config --enable CONFIG_HAS_LTO_CLANG" linux-lqx/PKGBUILD
#           sed -i -e "160i \ \t\tscripts/config --disable CONFIG_LTO_NONE" linux-lqx/PKGBUILD
#           sed -i -e "160i \ \t\tscripts/config --enable CONFIG_ARCH_SUPPORTS_LTO_CLANG_THIN" linux-lqx/PKGBUILD
#           sed -i -e "160i \ \t\tscripts/config --enable CONFIG_ARCH_SUPPORTS_LTO_CLANG" linux-lqx/PKGBUILD
#           sed -i -e "160i \ \t\tscripts/config --enable CONFIG_LTO_CLANG" linux-lqx/PKGBUILD
#           sed -i -e "160i \ \t\tscripts/config --enable CONFIG_LTO" linux-lqx/PKGBUILD
#      - name: Build kernel
#        run: |
#           docker run -e USERID=$(id -u $(whoami)) -e GITHUB_TOKEN=${{ secrets.pat }} -v $GITHUB_WORKSPACE:/workspace archlinux:latest /bin/bash /workspace/build-lqx.sh
#           cp $GITHUB_WORKSPACE/linux-lqx/*.pkg.tar.zst /tmp
#      - uses: actions/upload-artifact@v3
#        with:
#          name: linux-lqx
#          path: /tmp/*.pkg.tar.zst
