name: build-buildozer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkount repo
        uses: actions/checkout@v4 
      - name: Checkount buildozer
        uses: actions/checkout@v4
        with: 
          repository: kivy/buildozer
          ref: 1.5.0
          path: buildozer
      - name: Prepare for build
        run: |
          cd buildozer
          curl -LO https://raw.githubusercontent.com/kivy/buildozer/master/Dockerfile
          echo "sed -i 's/useradd/useradd -u $(id -u)/g' Dockerfile" | bash
          docker build --tag=kivy/buildozer .
          cd ..
          docker run --volume "$(pwd)":/home/user/hostcwd kivy/buildozer --version
#          sudo apt update
#          sudo apt upgrade -y
#          apt autoremove
#          apt autoclean
      - name: Build
        run : |
          cd sample
          docker run --volume "$(pwd)":/home/user/hostcwd kivy/buildozer init
          echo "android.permissions = android.permission.INTERNET" >> buildozer.spec
          sed -i "s/requirements = python3,kivy/requirements = python3,kivy,android/g" buildozer.spec
          yes | docker run -i --volume "$(pwd)":/home/user/hostcwd kivy/buildozer -v android debug
          mv bin/*.apk ..
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: ${{ github.workspace }}/*.apk
