name: build-buildozer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkount repo
        uses: actions/checkout@v4 
      - name: Checkount buildozer
        uses: actions/checkout@v4
        with: 
          repository: kivy/buildozer
          ref: 1.5.0
          path: buildozer
      - name: Checkount python-for-android
        uses: actions/checkout@v4
        with: 
          repository: kivy/python-for-android
          ref: release-2024.01.21
          path: python-for-android
      - name: Prepare for build
        run: |
          cd buildozer
          curl -LO https://raw.githubusercontent.com/kivy/buildozer/master/Dockerfile
          echo "sed -i 's/useradd/useradd -u $(id -u)/g' Dockerfile" | bash
          sed -i 's/autoconf/autoconf autopoint/g' Dockerfile
          docker build --tag=kivy/buildozer .
          cd ..
          docker run --volume "$(pwd)":/home/user/hostcwd kivy/buildozer --version
#          sudo apt update
#          sudo apt upgrade -y
#          apt autoremove
#          apt autoclean
      - name: Build
        run : |
          cd sample
          mv ../python-for-android .
          sed -i 's/<application android:label/<application android:usesCleartextTraffic="true" android:label/g' ./python-for-android/pythonforandroid/bootstraps/sdl2/build/templates/AndroidManifest.tmpl.xml
          docker run --volume "$(pwd)":/home/user/hostcwd kivy/buildozer init
          sed -i "s/requirements = python3,kivy/requirements = python3,kivy,android,aiofiles-23.2.1,altair-5.3.0,annotated-types-0.7.0,anyio-4.4.0,attrs-23.2.0,click-8.1.7,contourpy-1.2.1,cycler-0.12.1,dnspython-2.6.1,email_validator-2.1.1,fastapi-0.111.0,fastapi-cli-0.0.4,ffmpy-0.3.2,filelock-3.14.0,fonttools-4.53.0,fsspec-2024.6.0,gradio-4.36.0,gradio-client-1.0.1,h11-0.14.0,httpcore-1.0.5,httptools-0.6.1,httpx-0.27.0,huggingface-hub-0.23.3,importlib-resources-6.4.0,jinja2-3.1.4,jsonschema-4.22.0,jsonschema-specifications-2023.12.1,kiwisolver-1.4.5,markdown-it-py-3.0.0,markupsafe-2.1.5,matplotlib-3.9.0,mdurl-0.1.2,numpy-1.26.4,orjson-3.10.3,packaging-24.0,pandas-2.2.2,pillow-10.3.0,pydantic-2.7.3,pydantic-core-2.18.4,pydub-0.25.1,pyparsing-3.1.2,python-dateutil-2.9.0.post0,python-dotenv-1.0.1,python-multipart-0.0.9,pytz-2024.1,pyyaml-6.0.1,referencing-0.35.1,rich-13.7.1,rpds-py-0.18.1,ruff-0.4.8,semantic-version-2.10.0,shellingham-1.5.4,six-1.16.0,sniffio-1.3.1,starlette-0.37.2,tomlkit-0.12.0,toolz-0.12.1,tqdm-4.66.4,typer-0.12.3,typing-extensions-4.12.2,tzdata-2024.1,ujson-5.10.0,uvicorn-0.30.1,uvloop-0.19.0,watchfiles-0.22.0,websockets-11.0.3/g" buildozer.spec
          grep -v '^#' buildozer.spec | sed '/\[app\]/a android.permissions = android.permission.INTERNET' > tmp.spec
          mv tmp.spec buildozer.spec
          sed -i '/\[app\]/a p4a.source_dir = ./python-for-android' buildozer.spec
          cat buildozer.spec
          yes | docker run -i --volume "$(pwd)":/home/user/hostcwd kivy/buildozer -v android debug
          find .
          mv bin/*.apk ..
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: ${{ github.workspace }}/*.apk
