name: build-buildozer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkount repo
        uses: actions/checkout@v4 
      - name: Checkount buildozer
        uses: actions/checkout@v4
        with: 
          repository: kivy/buildozer
          ref: 1.5.0
          path: buildozer
      - name: Checkount python-for-android
        uses: actions/checkout@v4
        with: 
          repository: kivy/python-for-android
          ref: release-2024.01.21
          path: python-for-android
      - name: Prepare for build
        run: |
          cd buildozer
          curl -LO https://raw.githubusercontent.com/kivy/buildozer/master/Dockerfile
          echo "sed -i 's/useradd/useradd -u $(id -u)/g' Dockerfile" | bash
          sed -i 's/gettext/gettext-dev/g' Dockerfile
          docker build --tag=kivy/buildozer .
          cd ..
          docker run --volume "$(pwd)":/home/user/hostcwd kivy/buildozer --version
#          sudo apt update
#          sudo apt upgrade -y
#          apt autoremove
#          apt autoclean
      - name: Build
        run : |
          cd sample
          mv ../python-for-android .
          sed -i 's/<application android:label/<application android:usesCleartextTraffic="true" android:label/g' ./python-for-android/pythonforandroid/bootstraps/sdl2/build/templates/AndroidManifest.tmpl.xml
          docker run --volume "$(pwd)":/home/user/hostcwd kivy/buildozer init
          sed -i "s/requirements = python3,kivy/requirements = python3,kivy,android,pytz,pydub,ffmpy,websockets,uvloop,ujson,tzdata,typing-extensions,tqdm,toolz,tomlkit,sniffio,six,shellingham,semantic-version,ruff,rpds-py,pyyaml,python-multipart,python-dotenv,pyparsing,pillow,packaging,orjson,numpy,mdurl,markupsafe,kiwisolver,importlib-resources,httptools,h11,fsspec,fonttools,filelock,dnspython,cycler,click,attrs,annotated-types,aiofiles,uvicorn,referencing,python-dateutil,pydantic-core,markdown-it-py,jinja2,huggingface-hub,httpcore,email_validator,contourpy,anyio,watchfiles,starlette,rich,pydantic,pandas,matplotlib,jsonschema-specifications,httpx,typer,jsonschema,gradio-client,fastapi-cli,altair,fastapi,gradio/g" buildozer.spec
          grep -v '^#' buildozer.spec | sed '/\[app\]/a android.permissions = android.permission.INTERNET' > tmp.spec
          mv tmp.spec buildozer.spec
          sed -i '/\[app\]/a p4a.source_dir = ./python-for-android' buildozer.spec
          cat buildozer.spec
          yes | docker run -i --volume "$(pwd)":/home/user/hostcwd kivy/buildozer -v android debug
          find .
          mv bin/*.apk ..
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: ${{ github.workspace }}/*.apk
