name: build-chromium

on:
  workflow_dispatch:

env:
  PKGDEST: "/workspace/chromium"

jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkount repo
        uses: actions/checkout@v3
        with: 
          repository: archlinux/svntogit-packages
          ref: packages/chromium
          path: chromium
      - name: Prepare for makepkg
        run: |
          mv chromium /workspace
          chown builder -R /workspace
      - name: Build
        run: |
          cd /workspace/chromium/trunk/
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
      - uses: actions/upload-artifact@v3
        with:
          name: chromium
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
