name: build-chromium

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp/chromium"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Checkount repo
        uses: actions/checkout@v3
        with: 
          repository: archlinux/svntogit-packages
          ref: packages/chromium
          path: chromium
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown builder -R ..
          chown builder -R /tmp
      - name: Build
        run: |
          cd chromium/svntogit-packages/trunk/
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
      - uses: actions/upload-artifact@v3
        with:
          name: chromium
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
