name: diff

on:
  workflow_dispatch:

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkount aports repository
        uses: actions/checkout@v3  
        with:
          repository: ClangBuiltLinux/linux
          ref: srso-fixes
          path: linux
          fetch-depth: 0
      - name: Diff between commits
        run: |
          cd linux
          git diff HEAD^ > /tmp/commit.diff
      - uses: actions/upload-artifact@v3
        with:
          name: diff
          path: /tmp/commit.diff
