name: build-firejail

on:
  workflow_dispatch:
        
env:
  PKGDEST: "/tmp"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git          
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

          git clone --depth 1 https://gitlab.archlinux.org/archlinux/packaging/packages/firejail
          chown builder -R firejail
          chown builder -R /tmp
      - name: Build
        run: |
          cd firejail
          sed -i "s/--enable-apparmor/--enable-apparmor --enable overlayfs/g" PKGBUILD
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm --nocheck --skippgpcheck -sc"
      - name: Upload packages
        uses: actions/upload-artifact@v7
        with:
          name: firejail
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
