name: build-i3lock-color

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp/i3lock-color"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Checkount repo
        uses: actions/checkout@v4
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          git clone --depth 1 https://aur.archlinux.org/i3lock-color.git
          chown builder -R ..
          chown builder -R /tmp
      - name: Build
        run: |
          cd i3lock-color
          su builder -c "yes '' | makepkg --noconfirm -sc"
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: i3lock-color
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
