name: build-kwin-bismuth

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp/pkgbuild-kwin-bismuth"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          git clone https://aur.archlinux.org/kwin-bismuth.git
          chown builder -R ..
          chown builder -R /tmp
      - name: Build
        run: |
          cd kwin-bismuth
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
      - uses: actions/upload-artifact@v3
        with:
          name: kwin-bismuth
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
