name: build-kwin-polonium

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp/"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Checkount repo
        uses: actions/checkout@v4
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git zip
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          git clone --depth 1 https://aur.archlinux.org/kwin-polonium.git
          chown builder -R ..
          chown builder -R /tmp
      - name: Build
        run: |
          cd kwin-polonium
          su builder -c "yes '' | makepkg --noconfirm -sc"
          cd /tmp
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: kwin-polonium
          path: ${{ env.PKGDEST }}/*.zip
        
