name: build-libva-utils 

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp/libva-utils "
#  LIBVA_CFLAGS: "-g3"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Checkount repo
        uses: actions/checkout@v3
        with: 
          repository: archlinux/svntogit-packages
          ref: packages/libva
          path: libva
      - name: Prepare for build
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown builder -R ..
          chown builder -R /tmp
          sed -i 's/df3c584bb79d1a1e521372d62fa62e8b1c52ce6c/2.18.0/g' libva/trunk/PKGBUILD
          cd libva/trunk
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
          pacman -U $(ls -1 ${{ env.PKGDEST }}/libva*.pkg.tar.zst)
      - name: Checkount repo
        run: curl -LO https://raw.githubusercontent.com/archlinux/svntogit-community/packages/libva-utils/trunk/PKGBUILD
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown builder -R ..
          chown builder -R /tmp
          curl -LO https://github.com/intel/libva-utils/archive/2.18.0/libva-utils-2.18.0.tar.gz
          export NEW=$(sha256sum libva-utils-2.18.0.tar.gz | awk '{ print $1}')
          curl -LO https://github.com/intel/libva-utils/archive/2.17.1/libva-utils-2.17.1.tar.gz
          export OLD=$(sha256sum libva-utils-2.17.1.tar.gz | awk '{ print $1}')
          echo "sed -i 's/${OLD}/${NEW}/g' PKGBUILD" | bash
          sed -i 's/2.17.1/2.18.0/g' PKGBUILD
#          echo "options=(debug !strip)" >> PKGBUILD
      - name: Build
        run: |
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc" 
      - uses: actions/upload-artifact@v3
        with:
          name: libva-utils
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
