name: build-libva-utils 

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp/libva-utils "
  LIBVA_CFLAGS: "-g3"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Checkount repo
        run: curl -LO https://raw.githubusercontent.com/archlinux/svntogit-community/packages/libva-utils/trunk/PKGBUILD
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown builder -R ..
          chown builder -R /tmp
          sed -i -e '/arch-meson ${pkgname}-${pkgver} build/i  \ \ \ \ sed -i "s/+ m/+ -g3 + m/g" ./${pkgname}-${pkgver}/vainfo/meson.build' PKGBUILD
          sed "s/-g3/'-g3'/g" PKGBUILD
          sed -i 's/arch-meson ${pkgname}-${pkgver} build/arch-meson ${pkgname}-${pkgver} build --buildtype=debugoptimized/g' PKGBUILD 
      - name: Build
        run: |
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc" 
      - uses: actions/upload-artifact@v3
        with:
          name: libva-utils
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
