name: build-libva-intel-driver

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp/libva-intel-driver"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Checkount repo
        uses: actions/checkout@v3
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          curl -LO https://raw.githubusercontent.com/archlinux/svntogit-packages/packages/libva-intel-driver/trunk/PKGBUILD
          chown builder -R ..
          chown builder -R /tmp
      - name: Build
          su builder -c "yes '' | makepkg --noconfirm -sc"
      - uses: actions/upload-artifact@v3
        with:
          name: libva-intel-driver
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
