name: build-libva-utils 

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp/libva-utils "

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Checkount repo
        run: curl -LO https://raw.githubusercontent.com/archlinux/svntogit-community/packages/libva-utils/trunk/PKGBUILD
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown builder -R ..
          chown builder -R /tmp
          sed -i -e '/arch-meson ${pkgname}-${pkgver} build/i  \ \ \ \ sed -i "\/license : 'MIT',/i \ c_args:[''-g'']," ./${pkgname}-${pkgver}/meson.build' PKGBUILD
          sed -i "s/MIT/'MIT'/g" PKGBUILD
          sed -i "s/\[-g\]/'\[-g\]'/g" PKGBUILD
          sed -i -e '/arch-meson ${pkgname}-${pkgver} build/i  \ \ \ \ cat ./${pkgname}-${pkgver}/meson.build' PKGBUILD 
          sed -i 's/arch-meson ${pkgname}-${pkgver} build/arch-meson ${pkgname}-${pkgver} build --buildtype=debug/g' PKGBUILD 
      - name: Build
        run: |
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc" 
      - uses: actions/upload-artifact@v3
        with:
          name: libva-utils
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
