name: build-libva-arch

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp/libva"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Checkount repo
        uses: actions/checkout@v3
        with: 
          repository: archlinux/svntogit-packages
          ref: packages/libva
          path: libva
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown builder -R ..
          chown builder -R /tmp
          sed -i 's/df3c584bb79d1a1e521372d62fa62e8b1c52ce6c/2.18.0/g' libva/trunk/PKGBUILD
#          sed -i 's/git describe --tags/echo 2.18.0/g' libva/trunk/PKGBUILD
#          sed -i 's/intel\/libva.git#tag=${_tag}/evelikov\/libva.git#branch=rework-device-names/g' libva/trunk/PKGBUILD
#          echo "options=(debug !strip)" >> libva/trunk/PKGBUILD
#          sed -i -e '/arch-meson libva build/i  \ \ sed -i "s\/va_DRI3_Get\/va_DRI2_Get\/g" ./libva/va/x11/va_x11.c' libva/trunk/PKGBUILD
      - name: Build
        run: |
          cd libva/trunk
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc" 
      - uses: actions/upload-artifact@v3
        with:
          name: libva
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
