name: build-libva

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp/libva"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Checkount repo
        uses: actions/checkout@v3
        with: 
          repository: archlinux/svntogit-packages
          ref: packages/libva
          path: libva
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown builder -R ..
          chown builder -R /tmp
          sed -i -e '/arch-meson libva build/i  \ \ sed -i "s\/va_DRI3_GetNumCandidates\/va_DRI2_GetNumCandidates\/g" ./libva/va/x11/va_x11.c' libva/trunk/PKGBUILD 
#          sed -i 's/git describe --tags/echo "2.17.0"/g' libva/trunk/PKGBUILD
#          sed -i 's/df3c584bb79d1a1e521372d62fa62e8b1c52ce6c/ef1df02f3ad45ac98b1fa57c373176d7c14dcc57/g' libva/trunk/PKGBUILD
      - name: Build
        run: |
          cd libva/trunk
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc" 
      - uses: actions/upload-artifact@v3
        with:
          name: libva
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
