name: build-linux-lts

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
#    container: alpine:3.19
    steps:
      - name: Checkount repo
        uses: actions/checkout@v4
      - name: Cleanup
        run: |
          sh ./cleanup.sh
      - name: Checkout aports repository
        uses: actions/checkout@v4  
        with:
          repository: alpinelinux/aports
          ref: 3.20-stable
          path: aports
      - name: Move repo directory
        run: |
           mv aports/main/linux-lts .
           echo "USERID=$(id -u $(whoami))" >> $GITHUB_ENV
        env: 
          USERID: ''          
      - name: Build apk
        uses: docker://alpine:3.20
        with:
          entrypoint: '/bin/sh'
          args: ./build-linux-lts.sh ${{ env.USERID }} 
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: linux-lts
          path: ${{ github.workspace }}/linux-lts/*.apk
