name: build-linux-edge

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:3.18
    steps:
      - name: Install sdk
        run: |
          apk upgrade
          apk add alpine-sdk sudo
      - name: Checkount aports repository
        uses: actions/checkout@v3  
        with:
          repository: alpinelinux/aports
          ref: 3.18-stable
          path: aports
      - name: Prepare abuild
#          echo "permit nopass :wheel" >> /etc/doas.d/doas.conf      
        run: |
          adduser builder -D -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          addgroup builder abuild
          chown builder -R ..
          chown builder -R /tmp
          mkdir -p /var/cache/distfiles
          chmod a+w /var/cache/distfiles
          chgrp abuild /var/cache/distfiles
          chmod g+w /var/cache/distfiles
          su builder -c "abuild-keygen -a -i -n"
          apk add bash
      - name: Move repo directory
        run: |
           mv aports/community/linux-edge /home/builder
           cd /home/builder
           curl -LO https://raw.githubusercontent.com/mtak-misc/pkgbuild-linux-xanmod/main/per_vma_lock.patch
           chown builder -R /home/builder
           cd /home/builder/linux-edge
           sed -i -e '/unset LDFLAGS/i \ \tscripts/config -e CONFIG_MOUSE_PS2_SENTELIC' APKBUILD           
           curl -LO https://cdn.kernel.org/pub/linux/kernel/v6.x/patch-6.4.5.xz
           export NEW=$(sha512sum patch-6.4.5.xz)
           curl -LO https://cdn.kernel.org/pub/linux/kernel/v6.x/patch-6.4.4.xz
           export OLD=$(sha512sum patch-6.4.4.xz)
           sed -i 's/6.4.4/6.4.5/g' APKBUILD
           sed -i 's/${OLD}/${NEW}/g' APKBUILD           
      - name: Install packages
        run: |
           cd /home/builder/linux-edge
           su builder -c "abuild checksum"
           su builder -c "abuild deps"                
      - name: Build apk
        run: |
           cd /home/builder/linux-edge
           su builder -c "abuild"        
           cp $(find /home/builder -name linux-edge*.apk) /tmp
      - uses: actions/upload-artifact@v3
        with:
          name: linux-edge
          path: /tmp/*.apk
