name: build-linux-xanmod-bore

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp/linux-xanmod-bore"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Checkount repo
        uses: actions/checkout@v3
        with: 
          repository: micros24/linux-xanmod-bore
          ref: 6.4
          path: linux-xanmod-bore
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown builder -R ..
          chown builder -R /tmp
          su builder -c "gpg --recv 38DBBDC86092693E"
      - name: Build
        run: |
          cd linux-xanmod-bore
          su builder -c "yes '' | makepkg --noconfirm -sc" 
#          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc" 
      - uses: actions/upload-artifact@v3
        with:
          name: linux-xanmod-bore
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
