name: build-linux-lts

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
#    container: alpine:3.19
    steps:
      - name: Checkount repo
        uses: actions/checkout@v4
      - name: Cleanup
        run: |
          sh ./cleanup.sh
      - name: Checkount aports repository
        uses: actions/checkout@v4  
        with:
          repository: alpinelinux/aports
          ref: 3.19-stable
          path: aports
      - name: Move repo directory
        run: |
           mv aports/main/linux-lts .              
      - name: Build apk
        run: |
           cd /home/builder/linux-lts
           su builder -c "abuild"        
           cp $(find /home/builder -name linux-lts*.apk) /tmp
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: linux-lts
          path: /tmp/*.apk
