name: build-action

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp/maldet"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Checkount repo
        uses: actions/checkout@v3
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git clamav xz
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          git clone https://aur.archlinux.org/maldet.git
          chown builder -R ..
          chown builder -R /tmp
      - name: Build
        run: |
          cd maldet
          su builder -c "yes '' | makepkg --noconfirm -sc"
          pacman -U --noconfirm /tmp/maldet/maldet*.zst
#          tar -tf /tmp/maldet/maldet*.zst
#          cat /usr/lib/systemd/system/maldet.service
      - name: Undock container
        run: |
          curl -LO https://github.com/crazy-max/undock/releases/download/v0.3.0/undock_0.3.0_linux_amd64.tar.gz
          tar zxf undock_0.3.0_linux_amd64.tar.gz
          ./undock --include / --rm-dist --all selenium/hub:latest /tmp/hub
          ./undock --include / --rm-dist --all selenium/node-chrome:latest /tmp/node-chrome
          curl -LO https://secure.eicar.org/eicar.com
          chown builder:builder eicar.com
          mv eicar.com /tmp/hub/etc
      - name: Scan
        run: |
          freshclam
          /usr/bin/maldet --monitor /etc/maldet/monitor_paths
          maldet -d
          maldet -u
          maldet -a /tmp
      - uses: actions/upload-artifact@v3
        with:
          name: maldet
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
