name: build-action

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp/nvidia-390xx-settings.git"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Checkount repo
        uses: actions/checkout@v3
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          git clone https://aur.archlinux.org/nvidia-390xx-settings.git
          chown builder -R ..
          chown builder -R /tmp
      - name: Build
        run: |
          cd nvidia-390xx-settings.git
          sed -i 's/cbb6b5f69784f66155a08da786b98de1de8659aa1b42af1a5baca02031e8e21c5d001292188994e01986dd4fca24ec9b7b5fb56491bfab889e7448cdde55f8ba/03b8cfa287612eaa1699845136283fe1ec4a43212fb0b9d3d0682ce6dd51702fbdfc53c29ea9ebe914034d2c20abb35af7667e0314948842152efd746773771a/g' PKGBUILD
          sed -i 's/154/157/g' PKGBUILD
          su builder -c "yes '' | makepkg --noconfirm -sc"
      - uses: actions/upload-artifact@v3
        with:
          name: nvidia-390xx-settings
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
