name: build-nvidia

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp/nvidia-390xx"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Checkount repo
        uses: actions/checkout@v3
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          git clone https://aur.archlinux.org/nvidia-390xx-settings.git
          git clone https://aur.archlinux.org/nvidia-390xx-utils.git
          curl -L https://gist.githubusercontent.com/joanbm/77f0650d45747b9a4dc8e330ade2bf5c/raw/688b612624945926676de28059fe749203b4b549/nvidia-470xx-fix-linux-6.4.patch -o ./nvidia-390xx-utils/kernel-6.4.patch 
          export NEW=\"$(b2sum ./nvidia-390xx-utils/kernel-6.4.patch | awk '{ print $1}')\"
          export OLD=$(b2sum ./nvidia-390xx-utils/kernel-6.3.patch | awk '{ print $1}')
          sed -i -e '/\ \ \ \ \ \ \ \ kernel-6.3.patch/i \ \ \ \ \ \ \ \ kernel-6.4.patch' ./nvidia-390xx-utils/PKGBUILD
          echo "sed -i -e '/${OLD}/i \ \ \ \ \ \ \ \ ${NEW}' ./nvidia-390xx-utils/PKGBUILD" | bash
          cat ./nvidia-390xx-utils/PKGBUILD
          chown builder -R ..
          chown builder -R /tmp
      - name: Build utils
        run: |
          cd nvidia-390xx-utils
          su builder -c "yes '' | makepkg --noconfirm -sc"
          pacman -U --noconfirm $PKGDEST/nvidia-390xx-utils-390.157-3-x86_64.pkg.tar.zst
      - name: Build settings
        run: |
          cd nvidia-390xx-settings
          su builder -c "yes '' | makepkg --noconfirm -sc"
      - uses: actions/upload-artifact@v3
        with:
          name: nvidia-390xx
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
