name: build-nvidia

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp/nvidia-390xx"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Checkount repo
        uses: actions/checkout@v3
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          git clone https://aur.archlinux.org/nvidia-390xx-settings.git
          git clone https://aur.archlinux.org/nvidia-390xx-utils.git
          mv ./kernel-6.5-full.patch ./nvidia-390xx-utils/
          sed -i -e '/patch -Np1 -i ..\/kernel-6.4.patch/a \ \ \ \ patch -Np1 -i ..\/..\/kernel-6.5-full.patch' ./nvidia-390xx-utils/PKGBUILD
          chown builder -R ..
          chown builder -R /tmp
      - name: Build utils
        run: |
          cd nvidia-390xx-utils
          su builder -c "yes '' | makepkg --noconfirm -sc"
          pacman -U --noconfirm $PKGDEST/nvidia-390xx-utils-390.157-5-x86_64.pkg.tar.zst
      - name: Build settings
        run: |
          cd nvidia-390xx-settings
          su builder -c "yes '' | makepkg --noconfirm -sc"
      - uses: actions/upload-artifact@v3
        with:
          name: nvidia-390xx
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
