name: build-nvidia

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp/nvidia-390xx"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          cp pacman.conf.patch /tmp
          cd /etc
          cp pacman.conf pacman.conf.orig
          patch -Np1 -i pacman.conf.patch
          pacman -Syu --noconfirm gcc
          cp pacman.conf.orig pacman.conf
          cd
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          git clone --depth 1 https://aur.archlinux.org/nvidia-390xx-utils.git
          chown builder -R ..
          chown builder -R /tmp
#          curl -LO https://github.com/mtak-misc/test1/raw/main/kernel-6.6.patch
#          mv ./kernel-6.6.patch ./nvidia-390xx-utils/
#          sed -i -e 's/pkgrel=6/pkgrel=6.3/g' ./nvidia-390xx-utils/PKGBUILD
#          sed -i -e '/patch -Np1 -i ..\/kernel-6.5.patch/a \ \ \ \ patch -Np1 -i ..\/..\/kernel-6.6.patch' ./nvidia-390xx-utils/PKGBUILD
      - name: Build
        run: |
          cd nvidia-390xx-utils
          su builder -c "yes '' | makepkg --noconfirm -sc"
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: nvidia-390xx
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
