name: build-otpclient

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp/pkgbuild-otpclient"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown builder -R ..
          chown builder -R /tmp
#      - name: Import key
#        run: su builder -c "gpg --recv 4EC1EA64"
      - name: Checkout libcottp
        run: cd /home/builder ; su builder -c "git clone https://aur.archlinux.org/libcotp.git"
      - name: Build libcotp
        run: cd /home/builder/libcotp ; su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc" 
      - uses: actions/upload-artifact@v3
        with:
          name: libcotp
          path: ${{ env.PKGDEST }}/libcotp*.pkg.tar.zst
      - name: Install libcotp
        run: pacman -U --noconfirm ${{ env.PKGDEST }}/libcotp*.pkg.tar.zst
      - name: Checkout otpclient
        run: cd /home/builder ; su builder -c "git clone https://aur.archlinux.org/otpclient.git"
      - name: Build otpclient
        run: cd /home/builder/otpclient ; su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
      - uses: actions/upload-artifact@v3
        with:
          name: otpclient
          path: ${{ env.PKGDEST }}/otpclient*.pkg.tar.zst        
