name: build-procps-ng

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp/procps-ng"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          git clone --depth 1 https://gitlab.archlinux.org/archlinux/packaging/packages/procps-ng.git
          chown builder -R ..
          chown builder -R /tmp
          su builder -c "gpg --recv 022166C0FF3C84E3"
      - name: Apply patches
        run: |
          sed -i -e '/--disable-kill/i \ \ \ \ --disable-numa\\' procps-ng/PKGBUILD          
      - name: Build
        run: |
          cd procps-ng
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc" 
      - uses: actions/upload-artifact@v3
        with:
          name: procps-ng
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
