name: build-protonvpn

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp"
  BUILDPKGS: "/tmp/packages"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          mkdir ${BUILDPKGS}
          chown builder -R ..
          chown builder -R /tmp
      - name: Build python-proton-vpn-network-manager 
        run: |
          su builder -c "git clone --depth 1 https://aur.archlinux.org/python-proton-vpn-network-manager.git"  
          cd python-proton-vpn-network-manager
          sed -i 's/pkgver=0.7.0/pkgver=0.9.1/g' PKGBUILD
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
          pacman -U --noconfirm $(ls ${PKGDEST}/*.zst)
          mv ${PKGDEST}/*.zst ${BUILDPKGS}
#          sed -i 's/pkgrel=2/pkgrel=1/g' PKGBUILD
      - name: Build python-proton-vpn-api-core
        run: |
          su builder -c "git clone --depth 1 https://aur.archlinux.org/python-proton-vpn-api-core.git"  
          cd python-proton-vpn-api-core
          sed -i 's/pkgver=0.33.12/pkgver=0.35.5/g' PKGBUILD
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
          pacman -U --noconfirm $(ls ${PKGDEST}/*.zst)
          mv ${PKGDEST}/*.zst ${BUILDPKGS}
      - name: Build python-proton-core
        run: |
          su builder -c "git clone --depth 1 https://aur.archlinux.org/python-proton-core.git"  
          cd python-proton-core
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
          pacman -U --noconfirm $(ls ${PKGDEST}/*.zst)
          mv ${PKGDEST}/*.zst ${BUILDPKGS}
#      - name: Build python-proton-vpn-logger 
#        run: |
#          su builder -c "git clone --depth 1 https://aur.archlinux.org/python-proton-vpn-logger.git"  
#          cd python-proton-vpn-logger
#          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
#          pacman -U --noconfirm $(ls ${PKGDEST}/*.zst)
#          mv ${PKGDEST}/*.zst ${BUILDPKGS}
      - name: Build python-proton-vpn-killswitch-network-manager 
        run: |
          su builder -c "git clone --depth 1 https://aur.archlinux.org/python-proton-vpn-killswitch-network-manager.git"  
          cd python-proton-vpn-killswitch-network-manager
          sed -i 's/pkgver=0.5.4/pkgver=0.6.1/g' PKGBUILD
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
          pacman -U --noconfirm $(ls ${PKGDEST}/*.zst)
          mv ${PKGDEST}/*.zst ${BUILDPKGS}
      - name: Build python-proton-keyring-linux
        run: |
          su builder -c "git clone --depth 1 https://aur.archlinux.org/python-proton-keyring-linux.git"  
          cd python-proton-keyring-linux
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
          pacman -U --noconfirm $(ls ${PKGDEST}/*.zst)
          mv ${PKGDEST}/*.zst ${BUILDPKGS}
#      - name: Build python-proton-vpn-killswitch-network-manager-wireguard
#        run: |
#          su builder -c "git clone --depth 1 https://aur.archlinux.org/python-proton-vpn-killswitch-network-manager-wireguard.git"  
#          cd python-proton-vpn-killswitch-network-manager-wireguard
#          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
#          pacman -U --noconfirm $(ls ${PKGDEST}/*.zst)
#          mv ${PKGDEST}/*.zst ${BUILDPKGS}
      - name: Build python-proton-keyring-linux-secretservice
        run: |
          su builder -c "git clone --depth 1 https://aur.archlinux.org/python-proton-keyring-linux-secretservice.git"  
          cd python-proton-keyring-linux-secretservice
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
          pacman -U --noconfirm $(ls ${PKGDEST}/*.zst)
          mv ${PKGDEST}/*.zst ${BUILDPKGS}  
      - name: Build proton-vpn-gtk-app
        run: |
          su builder -c "git clone --depth 1 https://aur.archlinux.org/proton-vpn-gtk-app.git"  
          cd proton-vpn-gtk-app
          sed -i 's/pkgver=4.5.0/pkgver=4.6.0/g' PKGBUILD
          sed -i '/python-proton-vpn-logger/d' PKGBUILD
          sed -i '/python-proton-vpn-killswitch-network-manager-wireguard/d' PKGBUILD
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
          pacman -U --noconfirm $(ls ${PKGDEST}/*.zst)
          mv ${PKGDEST}/*.zst ${BUILDPKGS}
#          sed -i 's/pkgrel=2/pkgrel=1/g' PKGBUILD
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: protonvpn
          path: ${{ env.BUILDPKGS }}/*.zst
