name: build-protonvpn

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp"
  BUILDPKGS: "/tmp/packages"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          mkdir ${BUILDPKGS}
          chown builder -R ..
          chown builder -R /tmp
      - name: Build python-proton-vpn-connection
        run: |
          su builder -c "git clone https://aur.archlinux.org/python-proton-vpn-connection.git"  
          cd python-proton-vpn-connection
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
          pacman -U --noconfirm $(ls ${PKGDEST}/*.zst)
          mv ${PKGDEST}/*.zst ${BUILDPKGS}
      - name: Build python-proton-vpn-session
        run: |
          su builder -c "git clone https://aur.archlinux.org/python-proton-vpn-session.git"  
          cd python-proton-vpn-session
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
          pacman -U --noconfirm $(ls ${PKGDEST}/*.zst)
          mv ${PKGDEST}/*.zst ${BUILDPKGS}
      - name: Build python-proton-vpn-network-manager 
        run: |
          su builder -c "git clone https://aur.archlinux.org/python-proton-vpn-network-manager.git"  
          cd python-proton-vpn-network-manager 
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
          pacman -U --noconfirm $(ls ${PKGDEST}/*.zst)
          mv ${PKGDEST}/*.zst ${BUILDPKGS}
      - name: Build python-proton-vpn-network-manager-openvpn 
        run: |
          su builder -c "git clone https://aur.archlinux.org/python-proton-vpn-network-manager-openvpn.git"  
          cd python-proton-vpn-network-manager-openvpn
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
          pacman -U --noconfirm $(ls ${PKGDEST}/*.zst)
          mv ${PKGDEST}/*.zst ${BUILDPKGS}
      - name: Build python-proton-vpn-api-core
        run: |
          su builder -c "git clone https://aur.archlinux.org/python-proton-vpn-api-core.git"  
          cd python-proton-vpn-api-core
          sed -i 's/9c03fc30d3ff08559cab3644eadde027b029375d/59a1cf008333ae357ada2fc7128694c2288b88da/g' PKGBUILD
          sed -i 's/pkgver=0.20.1/pkgver=0.20.2/g' PKGBUILD
          sed -i 's/pkgrel=5/pkgrel=1/g' PKGBUILD
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
          pacman -U --noconfirm $(ls ${PKGDEST}/*.zst)
          mv ${PKGDEST}/*.zst ${BUILDPKGS}
      - name: Build python-proton-core
        run: |
          su builder -c "git clone https://aur.archlinux.org/python-proton-core.git"  
          cd python-proton-core
          sed -i 's/5e795e04094dff67c03c56f2f3de03ff43514cc4/f5038d94dc0d8f8ea7a8075bcdc092e27862624b/g' PKGBUILD
          sed -i 's/pkgrel=3/pkgrel=4/g' PKGBUILD
          sed -i 's/pkgver=0.1.15/pkgver=0.1.16/g' PKGBUILD
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
          pacman -U --noconfirm $(ls ${PKGDEST}/*.zst)
          mv ${PKGDEST}/*.zst ${BUILDPKGS}
      - name: Build python-proton-vpn-logger 
        run: |
          su builder -c "git clone https://aur.archlinux.org/python-proton-vpn-logger.git"  
          cd python-proton-vpn-logger
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
          pacman -U --noconfirm $(ls ${PKGDEST}/*.zst)
          mv ${PKGDEST}/*.zst ${BUILDPKGS}
      - name: Build python-proton-vpn-killswitch
        run: |
          su builder -c "git clone https://aur.archlinux.org/python-proton-vpn-killswitch.git"  
          cd python-proton-vpn-killswitch
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
          pacman -U --noconfirm $(ls ${PKGDEST}/*.zst)
          mv ${PKGDEST}/*.zst ${BUILDPKGS}
      - name: Build python-proton-vpn-killswitch-network-manager 
        run: |
          su builder -c "git clone https://aur.archlinux.org/python-proton-vpn-killswitch-network-manager.git"  
          cd python-proton-vpn-killswitch-network-manager 
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
          pacman -U --noconfirm $(ls ${PKGDEST}/*.zst)
          mv ${PKGDEST}/*.zst ${BUILDPKGS}
      - name: Build python-proton-keyring-linux
        run: |
          su builder -c "git clone https://aur.archlinux.org/python-proton-keyring-linux.git"  
          cd python-proton-keyring-linux
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
          pacman -U --noconfirm $(ls ${PKGDEST}/*.zst)
          mv ${PKGDEST}/*.zst ${BUILDPKGS}
      - name: Build python-proton-keyring-linux-secretservice
        run: |
          su builder -c "git clone https://aur.archlinux.org/python-proton-keyring-linux-secretservice.git"  
          cd python-proton-keyring-linux-secretservice
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
          pacman -U --noconfirm $(ls ${PKGDEST}/*.zst)
          mv ${PKGDEST}/*.zst ${BUILDPKGS}
      - name: Build proton-vpn-gtk-app
        run: |
          su builder -c "git clone https://aur.archlinux.org/proton-vpn-gtk-app.git"  
          cd proton-vpn-gtk-app
          sed -i 's/713324e9e4ee9f030c8115072cae379eb3340c42/1177067f7162e8e529942489fe7714d7b28ce295/g' PKGBUILD
          sed -i 's/pkgver=4.1.0/pkgver=4.1.3/g' PKGBUILD
          sed -i 's/pkgrel=10/pkgrel=1/g' PKGBUILD
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
          pacman -U --noconfirm $(ls ${PKGDEST}/*.zst)
          mv ${PKGDEST}/*.zst ${BUILDPKGS}
      - uses: actions/upload-artifact@v3
        with:
          name: protonvpn
          path: ${{ env.BUILDPKGS }}/*.zst
