name: build-qtile-arch

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Checkount repo
        uses: actions/checkout@v4
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git python-flit-core 
          pacman --noconfirm -U https://archlinux.org/packages/extra/x86_64/seatd/download/ https://archlinux.org/packages/extra/x86_64/xcb-util-errors/download/
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown builder -R ..
          chown builder -R /tmp          
      - name: Build Qtile
        run: |
          git clone https://gitlab.archlinux.org/archlinux/packaging/packages/qtile.git
          chown builder -R ./qtile
          cd qtile
          su builder -c "gpg --recv-keys 18D18F1BC464DCA3"
          sed -i '/.\/scripts\/ffibuild/i \ \ patch -Np1 -i ../../../libinput.patch' PKGBUILD
          sed -i '/.\/scripts\/ffibuild/i \ \ patch -Np1 -i ../../../inputs.patch' PKGBUILD
          sed -i 's/pkgver=0.26.0/pkgver=0.27.0/g' PKGBUILD
          sed -i 's/pkgrel=2/pkgrel=1/g' PKGBUILD
          grep SigLevel /etc/pacman.conf
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
      - name : Install Qtile
        run: |
           pacman --noconfirm -U /tmp/qtile*.pkg.tar.zst
      - name: Build Qtile-Extra
        run: |
          curl -L https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=qtile-extras -o PKGBUILD
          sed -i 's/pkgver=0.26.0/pkgver=0.27.0/g' PKGBUILD
          chown builder PKGBUILD
          su builder -c "gpg --recv-keys 58A9AA7C86727DF7"
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: qtile
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
