name: build-qtile-alpine

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:3.19    
    steps:
      - name: Install sdk
        run: |
          apk upgrade
          apk add alpine-sdk sudo  
      - name: Checkount aports repository
        uses: actions/checkout@v3  
        with:
          repository: alpinelinux/aports
          ref: 3.19-stable
          path: aports
      - name: Prepare abuild
#          echo "permit nopass :wheel" >> /etc/doas.d/doas.conf      
        run: |
          adduser builder -D -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          addgroup builder abuild
          chown builder -R ..
          chown builder -R /tmp
          mkdir -p /var/cache/distfiles
          chmod a+w /var/cache/distfiles
          chgrp abuild /var/cache/distfiles
          chmod g+w /var/cache/distfiles
          su builder -c "abuild-keygen -a -i -n"
      - name: Move repo directory
        run: |
           mv aports/testing/qtile /home/builder
           sed -i 's/pkgver=0.22.1/pkgver=0.24.0/g' /home/builder/qtile/APKBUILD
           sed -i 's/pkgrel=2/pkgrel=1/g' /home/builder/qtile/APKBUILD
           sed -i '/0001-use-xcffib-1.4.0-s-new-in-line-APIs.patch/d' /home/builder/qtile/APKBUILD
           chown builder -R /home/builder
      - name: Install packages
        run: |
           cd /home/builder/qtile
           su builder -c "abuild checksum"
           su builder -c "abuild deps"
#           sed -i 's/v3.18/edge/g' /etc/apk/repositories
#           apk update
#           apk fetch py3-cairocffi py3-cairocffi-pyc py3-xcffib py3-xcffib-pyc
#           sed -i 's/edge/v3.19/g' /etc/apk/repositories
#           apk update
#           apk add py3-cairocffi*.apk py3-xcffib*.apk
#           cp py3-cairocffi*.apk py3-xcffib*.apk /tmp
      - name: Build apk
        run: |
           cd /home/builder/qtile
           su builder -c "abuild"
           cp $(find /home/builder -name qtile*.apk) /tmp
      - uses: actions/upload-artifact@v3
        with:
          name: qtile
          path: /tmp/*.apk
