name: build-qtile-arch

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          git clone https://gitlab.archlinux.org/archlinux/packaging/packages/qtile.git
          chown builder -R ..
          chown builder -R /tmp
          su builder -c "gpg --recv-keys 1F713A69C898ED88"
          cd qtile
          sed -i '/cd $pkgname/a \ \ curl -L https://raw.githubusercontent.com/elParaguayo/qtile/a3992faa44ba88caac3742ef57327ace5904f7d0/libqtile/widget/statusnotifier.py -o ./libqtile/widget/statusnotifier.py' PKGBUILD
          cat PKGBUILD
      - name: Build
        run: |
          cd qtile
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc" 
      - uses: actions/upload-artifact@v3
        with:
          name: qtile
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
