name: build-qtile-arch

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Checkount repo
        uses: actions/checkout@v3    
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git python-flit-core 
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown builder -R ..
          chown builder -R /tmp          
      - name: Build python-xcffib
        run: |
          curl -LO https://gitlab.archlinux.org/archlinux/packaging/packages/python-xcffib/-/raw/main/PKGBUILD
          chown builder PKGBUILD
          sed -i 's/pkgver=1.2.0/pkgver=1.5.0/g' PKGBUILD
          sed -i 's/pkgrel=2/pkgrel=1/g' PKGBUILD
          sed -i 's/#commit=$_commit/#tag=v$pkgver/g' PKGBUILD
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
      - name : Install python-xcffib
        run: |
          pacman --noconfirm -U /tmp/python-xcffib*.pkg.tar.zst
      - name: Build python-cairocffi
        run: |
          curl -LO https://gitlab.archlinux.org/archlinux/packaging/packages/python-cairocffi/-/raw/main/PKGBUILD
          chown builder PKGBUILD
          sed -i 's/ab3e552bbf0f7452a722a4739972f52de5c4bc83fbd0d1c53ce330cb3a42ce173be748cf8febb43fd7bd040f8d52afd7093efba60a42aa75c3945730693c25e7/SKIP/g' PKGBUILD
          sed -i 's/pkgver=1.5.0/pkgver=1.6.1/g' PKGBUILD
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
      - name : Install python-cairocffi
        run: |
          pacman --noconfirm -U /tmp/python-cairocffi*.pkg.tar.zst
      - name: Build Qtile
        run: |
          git clone https://gitlab.archlinux.org/archlinux/packaging/packages/qtile.git
          chown builder -R ./qtile
          cd qtile
          su builder -c "gpg --recv-keys 18D18F1BC464DCA3"
          sed -i '/.\/scripts\/ffibuild/i \ \ patch -Np1 -i ../../../libinput.patch' PKGBUILD
          sed -i '/.\/scripts\/ffibuild/i \ \ patch -Np1 -i ../../../inputs.patch' PKGBUILD        
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
      - name : Install Qtile
        run: |
           pacman --noconfirm -U /tmp/qtile*.pkg.tar.zst
      - name: Build Qtile-Extra
        run: |
          curl -L https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=qtile-extras -o PKGBUILD
          chown builder PKGBUILD
          su builder -c "gpg --recv-keys 58A9AA7C86727DF7"
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
      - uses: actions/upload-artifact@v3
        with:
          name: qtile
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
