name: build-qtile-extras

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          curl -L https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=qtile-extras -o PKGBUILD
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown builder -R ..
          chown builder -R /tmp
          su builder -c "gpg --recv-keys 58A9AA7C86727DF7"
          sed -i '/cd "$pkgname"/a \ \ curl -L https://github.com/elParaguayo/qtile-extras/raw/860818063771b0216cdae75f86dbeeb682c3dabb/qtile_extras/popup/menu.py -o ./qtile_extras/popup/menu.py' PKGBUILD
          sed -i '/cd "$pkgname"/a \ \ curl -L https://github.com/elParaguayo/qtile-extras/raw/860818063771b0216cdae75f86dbeeb682c3dabb/qtile_extras/resources/dbusmenu/__init__.py -o ./qtile_extras/resources/dbusmenu/__init__.py' PKGBUILD
          sed -i '/cd "$pkgname"/a \ \ curl -L https://github.com/elParaguayo/qtile-extras/raw/860818063771b0216cdae75f86dbeeb682c3dabb/qtile_extras/widget/statusnotifier.py -o ./qtile_extras/widget/statusnotifier.py' PKGBUILD
      - name: Build
        run: |
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc" 
      - uses: actions/upload-artifact@v3
        with:
          name: qtile-extras
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
