name: build-qtile-arch

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Checkount repo
        uses: actions/checkout@v4
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git python-flit-core
          sed -i 's/SigLevel    = Required DatabaseOptional/SigLevel = Never/g' /etc/pacman.conf
          grep SigLevel /etc/pacman.conf
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown builder -R ..
          chown builder -R /tmp          
      - name: Build Qtile
        run: |
          curl -L https://github.com/qtile/qtile/commit/b7cb03a6b89818821667801cac7f2ebcf6c4d830.patch -o 4845.patch
          curl -L https://github.com/fjpavon/qtile/commit/b6993439be94fd84cdbeeffb3e52eb8d801caf8f.patch -o 4821.patch
          curl -LO https://patch-diff.githubusercontent.com/raw/qtile/qtile/pull/4854.patch 
          git clone https://gitlab.archlinux.org/archlinux/packaging/packages/qtile.git
          chown builder -R ./qtile
          cd qtile
          su builder -c "gpg --recv-keys 18D18F1BC464DCA3"
          sed -i '/.\/scripts\/ffibuild/i \ \ patch -Np1 -i ../../../4854.patch' PKGBUILD
          sed -i '/.\/scripts\/ffibuild/i \ \ patch -Np1 -i ../../../4821.patch' PKGBUILD
          sed -i '/.\/scripts\/ffibuild/i \ \ curl -LO https://raw.githubusercontent.com/qtile/qtile/465126fb5cb26759aa24b634bbf46f2b8de41a14/CHANGELOG' PKGBUILD
          sed -i '/.\/scripts\/ffibuild/i \ \ patch -Np1 -i ../../../4845.patch' PKGBUILD
          sed -i 's/wlroots libwlroots.so=12/wlroots0.17 libwlroots.so=12/g' PKGBUILD
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
#          sed -i 's/pkgver=0.26.0/pkgver=0.27.0/g' PKGBUILD
#          sed -i 's/pkgrel=2/pkgrel=1/g' PKGBUILD
#          sed -i 's/a57ad598203c1fbfe56130ceefb06d9223c99f4fc240fc05d2e3cf56b5f188fb6da27290d0b546f6c42ffcd541c14d398d80266d09f2f95a30e807c31066cbbc/SKIP/g' PKGBUILD
#          sed -i 's/721f7ce98fd526541939ededadba0666d9f7b7683c2f62f71039de5d83a9e79aedbca3a3531adcacb8ce5ff2e28d81b08169bbf71ba7e9ba9b7a2455a1a107a5/SKIP/g' PKGBUILD
      - name : Install Qtile
        run: |
           pacman --noconfirm -U /tmp/qtile*.pkg.tar.zst
      - name: Build Qtile-Extra
        run: |
          curl -L https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=qtile-extras -o PKGBUILD
          chown builder PKGBUILD
          su builder -c "gpg --recv-keys 58A9AA7C86727DF7"
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc"
#          sed -i 's/pkgver=0.26.0/pkgver=0.27.0/g' PKGBUILD
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: qtile
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
