name: build-scudo-malloc

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:3.18    
    steps:
      - name: Install sdk
        run: |
          apk upgrade
          apk add alpine-sdk sudo  
      - name: Checkount aports repository
        uses: actions/checkout@v3  
        with:
          repository: alpinelinux/aports
#          ref: 3.18-stable
          path: aports
      - name: Prepare abuild
#          echo "permit nopass :wheel" >> /etc/doas.d/doas.conf      
        run: |
          adduser builder -D -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          addgroup builder abuild
          chown builder -R ..
          chown builder -R /tmp
          mkdir -p /var/cache/distfiles
          chmod a+w /var/cache/distfiles
          chgrp abuild /var/cache/distfiles
          chmod g+w /var/cache/distfiles
          su builder -c "abuild-keygen -a -i -n"
      - name: Move repo directory
        run: |
           mv aports/main/scudo-malloc /home/builder
           chown builder -R /home/builder
      - name: Install packages
        run: |
           cd /home/builder/scudo-malloc
           su builder -c "abuild checksum"
           su builder -c "abuild deps"
      - name: Build apk
        run: |
           cd /home/builder/scudo-malloc
           su builder -c "abuild"        
           cp $(find /home/builder -name *.apk) /tmp
      - uses: actions/upload-artifact@v3
        with:
          name: scudo-malloc
          path: /tmp/*.apk
