name: build-sddm

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:3.18    
    steps:
      - name: Install sdk
        run: |
          apk upgrade
          apk add alpine-sdk sudo  
      - name: Checkount aports repository
        uses: actions/checkout@v3  
        with:
          repository: alpinelinux/aports
#          ref: 3.18-stable
          path: aports
      - name: Prepare abuild
#          echo "permit nopass :wheel" >> /etc/doas.d/doas.conf      
        run: |
          adduser builder -D -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          addgroup builder abuild
          chown builder -R ..
          chown builder -R /tmp
          mkdir -p /var/cache/distfiles
          chmod a+w /var/cache/distfiles
          chgrp abuild /var/cache/distfiles
          chmod g+w /var/cache/distfiles
          su builder -c "abuild-keygen -a -i -n"
      - name: Move repo directory
        run: |
           mv aports/community/sddm /home/builder
           mv aports/community/sddm-breeze /home/builder
           mv aports/community/sddm-kcm /home/builder
           mv aports/community/sddm-openrc /home/builder
           chown builder -R /home/builder
      - name: Install packages for sddm
        run: |
           cd /home/builder/sddm
           su builder -c "abuild checksum"
           su builder -c "abuild deps"
      - name: Build sddm
        run: |
           cd /home/builder/sddm
           su builder -c "abuild"
      - name: Install packages for sddm-breeze
        run: |
           apk add $(find /home/builder -name sddm-*.apk) 
           cd /home/builder/sddm-breeze
           su builder -c "abuild checksum"
           su builder -c "abuild deps"
      - name: Build sddm-breeze
        run: |
           cd /home/builder/sddm-breeze
           su builder -c "abuild"
      - name: Install packages for sddm-kcm
        run: |
           cd /home/builder/sddm-kcm
           su builder -c "abuild checksum"
           su builder -c "abuild deps"
      - name: Build sddm-kcm
        run: |
           cd /home/builder/sddm-kcm
           su builder -c "abuild"
      - name: Install packages for sddm-openrc
        run: |
           cd /home/builder/sddm-openrc
           su builder -c "abuild checksum"
           su builder -c "abuild deps"
      - name: Build sddm-openrc
        run: |
           cd /home/builder/sddm-openrc
           su builder -c "abuild"
           cp $(find /home/builder -name *.apk) /tmp
      - uses: actions/upload-artifact@v3
        with:
          name: sddm
          path: /tmp/*.apk
