name: search-file

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          curl -LO https://raw.githubusercontent.com/archlinux/svntogit-community/packages/intel-media-driver/trunk/PKGBUILD
          chown builder -R ..
          chown builder -R /tmp
      - name: Search
        run: su builder -c "pacman -Fy linuxefi"
        
