name: build-shim-signed

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp/shim-signed"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Checkount repo
        uses: actions/checkout@v4
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          git clone --depth 1 hhttps://aur.archlinux.org/shim-signed.git
          chown builder -R ..
          chown builder -R /tmp
      - name: Build
        run: |
          cd shim-signed
          su builder -c "yes '' | makepkg --noconfirm -sc"
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: shim-signed
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
