name: test

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp/libva"

jobs:
  build:
    runs-on: ubuntu-latest
#    container: 
#      image: archlinux:latest
#      volumes:
#        - /workspace:/workspace
    steps:
      - name: Checkount repo
        uses: actions/checkout@v4
        with: 
          repository: archlinux/svntogit-packages
          ref: packages/libva
          path: libva
      - name: Test
        run: |
          df -h
          pwd
          free -h
