name: tt-patch-test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkount repo
        uses: actions/checkout@v3
        with:
          repository: xanmod/linux
          path: linux
          ref: 6.1
      - name: Apply patches
        run: |
          curl -L https://raw.githubusercontent.com/hamadmarri/TT-CPU-Scheduler/master/patches/6.1/tt-6.1.patch -o tt.patch
          cd linux
          patch < ../tt.patch
#      - uses: actions/upload-artifact@v3
#        with:
#          name: linux-xanmod
#          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
